language: python
sudo: false
python:
  - "3.6"
  - "3.7-dev"
install:
  - python setup.py install
script:
  - python setup.py check
deploy:
  provider: pypi
  user: kirillsulim
  password:
    secure: "WmBFB0qbQNiXz5mDD0z7chxo7RdnRiA5c6wFqQE9JYrSu7i0dwDUFDWMNzVhVYLeigTXpRsSmR0/dvBx3rOfw2ZCBNKu1TxjY134Tvblr/zp26yRkSpjrfEvVVzRUZSHkVEUHeYGD2WIERnG0k0LOvrDVMZwRGZF6Bwo04Di677L3H2ProAuGjpZaRmSg0vPKKtCj+Q5MI3IOJ1kG43bZfBnQCJwnRwnR4MKtKBv3Y5iyuqLr3YJlECxPD+b/gLA/8icgTRsefmsdgXCnYu7NWdzLhkl4Y9X7YyxIQmL8NpbZaQ6TtiiS6OCaEHYChsFdIAWJv/sO6pV6Zt5hWbb+waQ4dnTUhIPkOjoN5D4lp0gj16Bh5hbDZn3hp6bLFY99CwY+H3J49b4NDBOGpxHAijjDblXmwEbeZnYJmNvg+Ee6zMC9OucFPoM8gOEGetRm3tK3c52rNt5Fn8Lnei7KilTSbQf/018zpGp6CFjOnv3islqSFL16WO9uuKjsrxiFebj/gLsEJBHUfFDItY4kgqe9KtrpDSgieAS3amhOO5MsQ+VreH5QorUdbJqeNrjfMD7TQ29AvZdksFI1VAfwVZSMgk2v3Kzhf9HHGPhBjpeIv4E5bMiM4RiAODK4nzQCDO5DYHD9gVVXurRUco5cBUr7oxtd7pOOCZRRxaQXSo="
  on:
    branch: master
  distributions: sdist bdist_wheel
